change class name and get wget path dynamically

diff --git a/pipeline/ck b/pipeline/ck
--- a/pipeline/ck
+++ b/pipeline/ck
@@ -5,7 +5,11 @@ KUBECONFDIR="/root/kubeconf"
 KUBECONFIGNAME="kubeconfig"
 KUBECONFIGURL=$1
 
-WGET="/usr/bin/wget"
+WGET=`which wget`
+if (echo ${WGET} | grep -E "not found") || (echo ${WGET} | grep -E "no ") ; then
+  echo "There is no wget installed or added into PATH"
+  exit 1
+fi
 
 echo "try to get kubeconfig ${KUBECONFIGURL}"
 
